services:

  app:
    image: node:20
    restart: unless-stopped
    command: npm run dev
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - .:/app

  postgres:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
