services:

  app:
    image: node:20
    restart: unless-stopped
    command: npm run dev
    working_dir: /app
    ports:
      - "${APP_PORT:-3000}:3000"
    environment:
      NITRO_DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
    volumes:
      - .:/app
      - type: tmpfs
        target: /tmp

  postgres:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
